// src/common/constants/error-codes.ts
// Machine-readable error codes — PRD-B00 Section 8 + PRD-B02 Section 11

export const ErrorCode = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  INVALID_SIGNED_URL: 'INVALID_SIGNED_URL',
  SPLIT_AMOUNT_MISMATCH: 'SPLIT_AMOUNT_MISMATCH',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_GROUP_HOST: 'NOT_GROUP_HOST',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // Not Found
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  PERIOD_NOT_FOUND: 'PERIOD_NOT_FOUND',
  PAYMENT_RECORD_NOT_FOUND: 'PAYMENT_RECORD_NOT_FOUND',

  // Conflict
  ALREADY_PAID: 'ALREADY_PAID',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',

  // Payment
  PERIOD_NOT_ACTIVE: 'PERIOD_NOT_ACTIVE',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
